server:
  port: 8888
  session.timeout: 60000
  servlet.contextpath: /ka
logging:
  level:
    root: error
    com.yc: info
    org.springframework: error
  file:
    path: ./logs
    name: yc.log

yc:
  tname: zy
  age: 26